[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; base-uri 'self'; connect-src 'self'; font-src 'self' fonts.gstatic.com; form-action 'self'; frame-src 'self' www.google.com; img-src 'self' data: maps.gstatic.com maps.googleapis.com; manifest-src 'self'; prefetch-src 'self'; script-src 'self' 'unsafe-inline' www.gstatic.com maps.googleapis.com www.google.com/recaptcha/api.js; style-src 'self' 'unsafe-inline' fonts.googleapis.com"

[[plugins]]
  package = "@netlify/plugin-gatsby"
